name: Test TSP Solver

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rust-lang/setup-rust-toolchain@v1
   
    - name: Build
      run: cargo build --release
     
    - name: Run tests
      run: cargo test
     
    - name: Test with 5 cities
      run: cargo run --release 5 42
     
    - name: Test with 7 cities
      run: cargo run --release 7 123
